version: '3'
services:
  postgres:
    container_name: anadep-postgres
    image: postgres:16
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - PGDATA=/data/postgres
    volumes:
      - ./postgres:/data/postgres
    expose:
      - 5432
    command: -p 5432
    deploy:
      restart_policy:
        condition: on-failure
        delay: 3s
        max_attempts: 5
        window: 60s
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 10s
      retries: 10
    networks:
        - anadep-network

  backend:
    container_name: anadep-backend
    build: ./backend
    depends_on:
      - postgres
    ports:
      - 8080:8080
    environment:
      - SPRING_SECURITY_USER_NAME=${SPRING_SECURITY_USER_NAME}
      - SPRING_SECURITY_USER_PASSWORD=${SPRING_SECURITY_USER_PASSWORD}
      - SPRING_DATASOURCE_URL=jdbc:postgresql://anadep-postgres:5432/${POSTGRES_DB}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=${SPRING_JPA_HIBERNATE_DDL_AUTO}
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=${SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT}
      - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
      - GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}
      - URL_UICLIENT=http://localhost:3000
      - URL_ANADEPCLIENT=http://host.docker.internal:8081
      - ANADEP_DB_ENABLE=true
    deploy:
      restart_policy:
        condition: on-failure
        delay: 3s
        max_attempts: 5
        window: 60s
    networks:
        - anadep-network

  frontend:
    container_name: anadep-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - REACT_APP_BASE_URL=http://localhost:8080
        - REACT_APP_AUTH_SCOPE=repo
        - REACT_APP_AUTH_CLIENT_ID=${GITHUB_CLIENT_ID}
        - REACT_APP_ENABLE_ANADEP_DB=true
        - DEV_TOOLS=false
    ports:
      - 3000:80
    depends_on:
      - backend
    deploy:
      restart_policy:
        condition: on-failure
        delay: 3s
        max_attempts: 5
        window: 60s
    networks:
        - anadep-network

networks:
  anadep-network:
    driver: bridge