spring:
  application:
    name: anadep-scheduler
  cloud:
    aws:
      credentials:
        access-key:
        secret-key:
      region:
        static:
      dynamodb:
        endpoint:

management:
  endpoints:
    web:
      exposure:
        include: health

server:
  port: 8081

schedule:
  cron:
    expression: 0 0 0 * * *

