server:
  port: 8080

library:
  available-fix:
    enable: true
  custom-fix:
    enable: false

url:
  mavenClient: https://search.maven.org
  osvClient: https://api.osv.dev
  githubClient: https://api.github.com
  uiClient: http://localhost:3000
  osvStorage:
    npm: https://www.googleapis.com/storage/v1/b/osv-vulnerabilities

spring:
#  data:
#    mongodb:
#      uri:
  datasource:
    url:
    username:
    password:
  jpa:
    hibernate:
      ddl-auto:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  main:
    allow-bean-definition-overriding: true
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  security:
    user:
      name:
      password:

